### ISSUE TITLE
Change channel for join message.

### ISSUE THREAD

**Issue by Webhobo** [AppleDiscord/Siri-Bot#2]
Learn how to set it to specific channels either by command or changing the code. Will have to be reconfigured before release as it will be added to Apple Discord (while being in Siri Testing).

**Comment by jaacks** [comment]
you're looking for `m.guild.channels.find('name', 'channel-name').sendMessage("welcome msg")`

**Comment by Webhobo** [comment]
Thanks for all the help @jaacks :D
